spring.application.name=auth-service
server.port=8081

# Conexión a la base de datos con variables de entorno
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/quickbite_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:} # Ajusta si tu Laragon no tiene contraseña

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Propiedades del JWT
jwt.secret=QuickBiteSecretKeyForJwtAuthentication2026SuperSecret
jwt.expiration=86400000

# Conexión al Registro de Eureka para que el Gateway lo encuentre
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Rutas de OpenAPI (Swagger) de Auth para que el Gateway las capture
springdoc.api-docs.path=/v3/api-docs