version: '3.8'

services:
  # 1. Tu microservicio de Notificaciones
  notificaciones-service:
    build:
      context: ./PlataformaCurso/Notificaciones # <- Cambia esto por la ruta real a la carpeta de tu servicio de notificaciones
      dockerfile: Dockerfile
    container_name: notificaciones_app
    ports:
      - "8086:8086" # Mapea el puerto local al contenedor
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Por si usan perfiles de Spring
    networks:
      - plataforma-network

  # 2. Tu microservicio de Auth (Aunque no lo subas a AWS, para la nota local lo necesitas levantado)
  auth-service:
    build:
      context: ./PlataformaCurso/Auth # <- Cambia esto por la ruta real a la carpeta de tu servicio de Auth
      dockerfile: Dockerfile
    container_name: auth_app
    ports:
      - "8080:8080" # O el puerto que use tu Auth
    networks:
      - plataforma-network

networks:
  plataforma-network:
    driver: bridge
