# ==========================================
# Información del Servicio
# ==========================================
spring.application.name=notificacion-service
server.port=${SERVER_PORT:8086}

# ==========================================
# Base de Datos MySQL
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/db_plataforma_notifications?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin}

# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ==========================================
# Flyway
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.create-schemas=true

# ==========================================
# JWT
# ==========================================
jwt.secret=PlataformaCursoSecretKeyForJwtAuthentication2026SuperSecret
jwt.expiration=86400000

# ==========================================
# Swagger
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================
# Eureka
# ==========================================
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true