# Informaci�n del Servicio
spring.application.name=usuario-service
server.port=8082

# Configuraci�n de Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/plataformacurso_usuario?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Migraciones Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Seguridad JWT
jwt.secret=PlataformaCursoSecretKeyForJwtAuthentication2026SuperSecret
jwt.expiration=86400000

# Documentaci�n API (Swagger/Springdoc)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================
# Configuraci�n de Cliente Eureka
# ==========================================
# Indica d�nde encontrar el Servidor Eureka para registrarse
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Permite que este microservicio se registre en Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
